# default mmpack configuration file

# ordered list of remotes to look for packages
remotes:
    - http://mmpack-server-1:8888/
    - http://mmpack-server-2:8888/

# designed to look like this (eg with one foo package) :
# .mmpack
# ├── build
# │   └── foo
# │       ├── XXX
# │       ├── ...
# │       └── XXX
# ├── packages
# │   ├── foo-dev.mmpack
# │   ├── foo.mmpack
# │   └── foo-src.mmpack
# └── sources
#     └── foo-src.tar.gz
mmpack-build-path: ~/mmpack/
